---
- include: set_host_facts.yml

- include: packages.yml

- include: paxctl.yml
  when: grsecurity_install_set_paxctl_flags == true

- include: grub_config.yml

- include: validate_install.yml
  when: grsecurity_install_desired_kernel_version != ansible_kernel and
        grsecurity_install_reboot == true

- name: Display message about required reboot.
  debug:
    msg: >-
      Installed grsecurity-patched kernel version '{{ grsecurity_install_desired_kernel_version }}'.
      You must reboot the host to load the new kernel.
  when: grsecurity_install_desired_kernel_version != ansible_kernel and
        grsecurity_install_reboot == false
