---
- include: set_host_facts.yml

- include: packages.yml

- include: paxctl.yml
  when: grsecurity_install_set_paxctl_flags == true

- include: grub_config.yml

- include: validate_install.yml
  when: grsecurity_install_desired_kernel_version != ansible_kernel

