---
- name: Get GRUB menu options as host facts.
  action: grub_menu_options

  # Role requires that `grsecurity_install_deb_package` be defined.
- name: Check filename for deb package.
  fail:
    msg: >
      No deb package specified for installation.
      Define the variable 'grsecurity_install_deb_package'
      with the filepath to the local .deb package,
      then rerun the playbook.
  when: grsecurity_install_deb_package is not defined or
        grsecurity_install_deb_package == ''

- name: Set desired kernel version as host fact.
  set_fact:
    grsecurity_install_desired_kernel_version: "{{ grsecurity_install_deb_package | extract_kernel_version }}"

  # Sanity check to ensure that the filter above worked.
- name: Fail if desired kernel version as not found.
  fail:
    msg: >
      Could not find desired grsecurity kernel version. Check the filepath
      specified by `grsecurity_install_deb_package` and make sure it matches
      the regular expression 'linux-image-[\d.]+-grsec'.
  when: grsecurity_install_desired_kernel_version is not defined or
        grsecurity_install_desired_kernel_version == ''
